name: Build

on:
  pull_request:

  workflow_dispatch:
    branches: [ '**' ]

jobs:
  lodestar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        shell: bash
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: Docker build & push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: false
          platforms: linux/amd64
